# Ten plik skryptu spowoduje czystą instalację zależności węzłowych, zcache'uje je, przywróci, skompiluje kod źródłowy i uruchomi testy w różnych wersjach węzła.
# Więcej informacji można znaleźć tutaj: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ['bonafidebot', 'bot-api-messages']
        node-version: [10.x, 12.x]
        # Zobacz harmonogram obsługiwanego wydania Node.js na stronie https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        working-directory: ${{ matrix.dir }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Run tests
      run: npm test
